name: anvio-dev
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python=3.12
- pip
- setuptools
- wheel
- sqlite
- numpy
- scipy
- pandas
- scikit-learn
- matplotlib-base
- statsmodels
- bottle
- pysam
- ete3
- legacy-cgi
- django
- requests
- mistune
- six
- colored
- tabulate
- rich-argparse
- paste
- psutil
- snakemake
- multiprocess
- plotext
- networkx
- pyrodigal-gv
- pulp
- biopython
- reportlab
- pymupdf
- pyani
- llvmlite
- numba
- prodigal
- idba
- mcl
- muscle
- famsa
- hmmer
- diamond
- blast
- megahit
- spades
- flye
- minimap2
- bowtie2
- bwa
- graphviz
- "samtools>=1.9"
- trimal
- iqtree
- trnascan-se
- fasttree
- vmatch
- r-base
- r-tidyverse
- r-optparse
- r-stringi
- r-magrittr
- bioconductor-qvalue
- "meme>=5.5"
- fastani
- sra-tools
- pigz
- mmseqs2
- ghostscript
- nodejs
- pip:
  - "illumina-utils>=2.14,<3"
